// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactImagesUpload = require("react-images-upload");

function App(Props) {
  return React.createElement("div", undefined, React.createElement(ReactImagesUpload.default, {
                  withPreview: true,
                  withIcon: true,
                  buttonText: "Choose a image",
                  imgExtension: /* array */[
                    "png",
                    "jpeg"
                  ],
                  maxFileSize: 5242880
                }));
}

var make = App;

exports.make = make;
/* react Not a pure module */
